# Generated by Django 5.2.16 on 2026-10-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0022_order_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('business_name', models.CharField(max_length=255, verbose_name='razon social')),
                ('activity', models.CharField(max_length=255, verbose_name='giro')),
                ('address', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_request', to='orders.order')),
            ],
            options={
                'verbose_name': 'datos de factura',
                'verbose_name_plural': 'datos de factura',
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('voucher', 'Comprobante de pago (vale como boleta)'), ('boleta', 'Boleta electrónica'), ('factura', 'Factura electrónica')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('issued', 'Emitido'), ('failed', 'Falló')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('folio', models.CharField(blank=True, default='', max_length=40)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_documents', to='orders.order')),
            ],
            options={
                'verbose_name': 'documento tributario',
                'verbose_name_plural': 'documentos tributarios',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'kind'), name='one_tax_document_per_order_and_kind')],
            },
        ),
    ]
