# Generated by Django 5.2.16 on 2026-07-22 15:51

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def seed_generic_product_data(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    Joyas = apps.get_model('product', 'Joyas')
    Piedras = apps.get_model('product', 'Piedras')
    Attribute = apps.get_model('product', 'Attribute')
    AttributeValue = apps.get_model('product', 'AttributeValue')
    ProductAttributeValue = apps.get_model('product', 'ProductAttributeValue')
    ProductVariant = apps.get_model('product', 'ProductVariant')

    attribute_specs = {
        'material': ('Material', '', 'select', True, 10),
        'peso': ('Peso', 'g', 'decimal', False, 20),
        'largo': ('Largo', 'cm', 'decimal', False, 30),
        'ancho': ('Ancho', 'cm', 'decimal', False, 40),
        'alto': ('Alto', 'cm', 'decimal', False, 50),
        'nombre-piedra': ('Nombre piedra', '', 'select', True, 60),
        'dureza-mohs': ('Dureza Mohs', 'Mohs', 'decimal', False, 70),
        'origen': ('Origen', '', 'select', False, 80),
    }
    attributes = {}
    for slug, (name, unit, kind, is_variant_option, sort_order) in attribute_specs.items():
        attributes[slug], _ = Attribute.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'unit': unit,
                'kind': kind,
                'is_variant_option': is_variant_option,
                'sort_order': sort_order,
            },
        )

    def ensure_product_base(product, product_type=None):
        category_type = getattr(product.category, 'ProductType', '') if product.category_id else ''
        next_product_type = product_type or slugify(category_type) or 'general'
        base_slug = slugify(product.name) or 'producto'
        Product.objects.filter(pk=product.pk).update(
            slug=f'{base_slug}-{product.pk}',
            product_type=next_product_type,
        )
        ProductVariant.objects.get_or_create(
            product_id=product.pk,
            sku=f'PR-{product.pk}',
            defaults={'stock': 0 if product.sold else 1, 'is_active': True},
        )

    def attach_value(product_id, attribute, value, numeric_value=None):
        if value in (None, ''):
            return
        attribute_value, created = AttributeValue.objects.get_or_create(
            attribute=attribute,
            value=str(value),
            defaults={'numeric_value': numeric_value},
        )
        if not created and numeric_value is not None and attribute_value.numeric_value is None:
            attribute_value.numeric_value = numeric_value
            attribute_value.save(update_fields=['numeric_value'])
        ProductAttributeValue.objects.get_or_create(
            product_id=product_id,
            attribute_value=attribute_value,
        )

    for product in Product.objects.select_related('category').all():
        ensure_product_base(product)

    for joya in Joyas.objects.select_related('material', 'category').all():
        ensure_product_base(joya, 'joya')
        attach_value(joya.pk, attributes['material'], joya.material.name)
        attach_value(joya.pk, attributes['peso'], joya.weight, joya.weight)

    for piedra in Piedras.objects.select_related('nombrePiedra', 'category').all():
        ensure_product_base(piedra, 'piedra')
        attach_value(piedra.pk, attributes['largo'], piedra.large, piedra.large)
        attach_value(piedra.pk, attributes['ancho'], piedra.width, piedra.width)
        attach_value(piedra.pk, attributes['alto'], piedra.height, piedra.height)
        attach_value(piedra.pk, attributes['nombre-piedra'], piedra.nombrePiedra.name)
        attach_value(piedra.pk, attributes['dureza-mohs'], piedra.nombrePiedra.mohs, piedra.nombrePiedra.mohs)
        attach_value(piedra.pk, attributes['origen'], piedra.nombrePiedra.origen)


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_generic_product_variants'),
        ('product', '0008_alter_product_compare_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('kind', models.CharField(choices=[('select', 'Selección'), ('text', 'Texto'), ('integer', 'Entero'), ('decimal', 'Decimal')], default='select', max_length=20)),
                ('is_variant_option', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.SlugField(default='general', max_length=55),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='published', max_length=20),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.attribute')),
            ],
            options={
                'ordering': ['attribute__sort_order', 'sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('price_override', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'ordering': ['product_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='variants', through='product.ProductVariantAttributeValue', to='product.attributevalue'),
        ),
        migrations.RunPython(seed_generic_product_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_value_per_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_value'), name='unique_attribute_value_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute_value'), name='unique_attribute_value_per_variant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('product', 'sku'), name='unique_variant_sku_per_product'),
        ),
    ]
