# Generated by Django 5.2.17 on 2026-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_generic_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.SlugField(choices=[('joya', 'Joya'), ('piedra', 'Piedra'), ('general', 'Sin clasificar')], default='general', max_length=55),
        ),
    ]
