# Generated by Django 5.2.17 on 2026-09-24 14:20

"""Borra las subclases `Joyas`/`Piedras` y sus tablas relacionales.

Los datos ya viajaron a `ProductAttributeValue` en 0012. Las piezas siguen
existiendo como `Product`: la herencia multitabla solo agregaba una fila hija
con los campos propios, que ahora son atributos de categoria.

`RelationPiedraJoya` y `JoyaMateriales` se van con ellas: nunca tuvieron filas
y modelaban lo mismo (que una joya lleva tal piedra o tal material).
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_subclasses_to_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joyas',
            name='material',
        ),
        migrations.RemoveField(
            model_name='joyas',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='relationpiedrajoya',
            name='joya',
        ),
        migrations.RemoveField(
            model_name='piedras',
            name='nombrePiedra',
        ),
        migrations.RemoveField(
            model_name='piedras',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='relationpiedrajoya',
            name='nombrePiedra',
        ),
        migrations.DeleteModel(
            name='JoyaMateriales',
        ),
        migrations.DeleteModel(
            name='Joyas',
        ),
        migrations.DeleteModel(
            name='Piedras',
        ),
        migrations.DeleteModel(
            name='RelationPiedraJoya',
        ),
    ]
