# Generated by Django 5.2.16 on 2026-07-19 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('kind', models.CharField(choices=[('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo'), ('felicitacion', 'Felicitación'), ('otro', 'Otro')], default='sugerencia', max_length=20)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('reviewed', 'Revisada'), ('archived', 'Archivada')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
