# Generated by Django 5.2.16 on 2026-07-22 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payments_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_method_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payments',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo'), ('unknown', 'Desconocido')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='payments',
            name='status_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payments',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
