CHILE_REGIONS = [
    {
        'number': 15,
        'roman': 'XV',
        'name': 'Arica y Parinacota',
        'capital': 'Arica',
        'communes': ['Arica', 'Camarones', 'General Lagos', 'Putre'],
    },
    {
        'number': 1,
        'roman': 'I',
        'name': 'Tarapacá',
        'capital': 'Iquique',
        'communes': [
            'Alto Hospicio', 'Camiña', 'Colchane', 'Huara', 'Iquique',
            'Pica', 'Pozo Almonte',
        ],
    },
    {
        'number': 2,
        'roman': 'II',
        'name': 'Antofagasta',
        'capital': 'Antofagasta',
        'communes': [
            'Antofagasta', 'Calama', 'María Elena', 'Mejillones', 'Ollagüe',
            'San Pedro de Atacama', 'Sierra Gorda', 'Taltal', 'Tocopilla',
        ],
    },
    {
        'number': 3,
        'roman': 'III',
        'name': 'Atacama',
        'capital': 'Copiapó',
        'communes': [
            'Alto del Carmen', 'Caldera', 'Chañaral', 'Copiapó',
            'Diego de Almagro', 'Freirina', 'Huasco', 'Tierra Amarilla',
            'Vallenar',
        ],
    },
    {
        'number': 4,
        'roman': 'IV',
        'name': 'Coquimbo',
        'capital': 'La Serena',
        'communes': [
            'Andacollo', 'Canela', 'Combarbalá', 'Coquimbo', 'Illapel',
            'La Higuera', 'La Serena', 'Los Vilos', 'Monte Patria', 'Ovalle',
            'Paiguano', 'Punitaqui', 'Río Hurtado', 'Salamanca', 'Vicuña',
        ],
    },
    {
        'number': 5,
        'roman': 'V',
        'name': 'Valparaíso',
        'capital': 'Valparaíso',
        'communes': [
            'Algarrobo', 'Cabildo', 'Calera', 'Calle Larga', 'Cartagena',
            'Casablanca', 'Catemu', 'Concón', 'El Quisco', 'El Tabo',
            'Hijuelas', 'Isla de Pascua', 'Juan Fernández', 'La Cruz',
            'La Ligua', 'Limache', 'Llaillay', 'Los Andes', 'Nogales',
            'Olmué', 'Panquehue', 'Papudo', 'Petorca', 'Puchuncaví',
            'Putaendo', 'Quillota', 'Quilpué', 'Quintero', 'Rinconada',
            'San Antonio', 'San Esteban', 'San Felipe', 'Santa María',
            'Santo Domingo', 'Valparaíso', 'Villa Alemana', 'Viña del Mar',
            'Zapallar',
        ],
    },
    {
        'number': 13,
        'roman': 'RM',
        'name': 'Metropolitana de Santiago',
        'capital': 'Santiago',
        'communes': [
            'Alhué', 'Buin', 'Calera de Tango', 'Cerrillos', 'Cerro Navia',
            'Colina', 'Conchalí', 'Curacaví', 'El Bosque', 'El Monte',
            'Estación Central', 'Huechuraba', 'Independencia',
            'Isla de Maipo', 'La Cisterna', 'La Florida', 'La Granja',
            'La Pintana', 'La Reina', 'Lampa', 'Las Condes', 'Lo Barnechea',
            'Lo Espejo', 'Lo Prado', 'Macul', 'Maipú', 'María Pinto',
            'Melipilla', 'Ñuñoa', 'Padre Hurtado', 'Paine',
            'Pedro Aguirre Cerda', 'Peñaflor', 'Peñalolén', 'Pirque',
            'Providencia', 'Pudahuel', 'Puente Alto', 'Quilicura',
            'Quinta Normal', 'Recoleta', 'Renca', 'San Bernardo',
            'San Joaquín', 'San José de Maipo', 'San Miguel', 'San Pedro',
            'San Ramón', 'Santiago', 'Talagante', 'Tiltil', 'Vitacura',
        ],
    },
    {
        'number': 6,
        'roman': 'VI',
        'name': "Libertador General Bernardo O'Higgins",
        'capital': 'Rancagua',
        'communes': [
            'Chépica', 'Chimbarongo', 'Codegua', 'Coínco', 'Coltauco',
            'Doñihue', 'Graneros', 'La Estrella', 'Las Cabras', 'Litueche',
            'Lolol', 'Machalí', 'Malloa', 'Marchihue', 'Mostazal',
            'Nancagua', 'Navidad', 'Olivar', 'Palmilla', 'Paredones',
            'Peralillo', 'Peumo', 'Pichidegua', 'Pichilemu', 'Placilla',
            'Pumanque', 'Quinta de Tilcoco', 'Rancagua', 'Rengo',
            'Requínoa', 'San Fernando', 'San Vicente', 'Santa Cruz',
        ],
    },
    {
        'number': 7,
        'roman': 'VII',
        'name': 'Maule',
        'capital': 'Talca',
        'communes': [
            'Cauquenes', 'Chanco', 'Colbún', 'Constitución', 'Curepto',
            'Curicó', 'Empedrado', 'Hualañé', 'Licantén', 'Linares',
            'Longaví', 'Maule', 'Molina', 'Parral', 'Pelarco', 'Pelluhue',
            'Pencahue', 'Rauco', 'Retiro', 'Río Claro', 'Romeral',
            'Sagrada Familia', 'San Clemente', 'San Javier', 'San Rafael',
            'Talca', 'Teno', 'Vichuquén', 'Villa Alegre', 'Yerbas Buenas',
        ],
    },
    {
        'number': 16,
        'roman': 'XVI',
        'name': 'Ñuble',
        'capital': 'Chillán',
        'communes': [
            'Bulnes', 'Chillán', 'Chillán Viejo', 'Cobquecura', 'Coelemu',
            'Coihueco', 'El Carmen', 'Ninhue', 'Ñiquén', 'Pemuco', 'Pinto',
            'Portezuelo', 'Quillón', 'Quirihue', 'Ránquil', 'San Carlos',
            'San Fabián', 'San Ignacio', 'San Nicolás', 'Treguaco', 'Yungay',
        ],
    },
    {
        'number': 8,
        'roman': 'VIII',
        'name': 'Biobío',
        'capital': 'Concepción',
        'communes': [
            'Alto Biobío', 'Antuco', 'Arauco', 'Cabrero', 'Cañete',
            'Chiguayante', 'Concepción', 'Contulmo', 'Coronel',
            'Curanilahue', 'Florida', 'Hualpén', 'Hualqui', 'Laja', 'Lebu',
            'Los Álamos', 'Los Ángeles', 'Lota', 'Mulchén', 'Nacimiento',
            'Negrete', 'Penco', 'Quilaco', 'Quilleco', 'San Pedro de la Paz',
            'San Rosendo', 'Santa Bárbara', 'Santa Juana', 'Talcahuano',
            'Tirúa', 'Tomé', 'Tucapel', 'Yumbel',
        ],
    },
    {
        'number': 9,
        'roman': 'IX',
        'name': 'La Araucanía',
        'capital': 'Temuco',
        'communes': [
            'Angol', 'Carahue', 'Cholchol', 'Collipulli', 'Cunco',
            'Curacautín', 'Curarrehue', 'Ercilla', 'Freire', 'Galvarino',
            'Gorbea', 'Lautaro', 'Loncoche', 'Lonquimay', 'Los Sauces',
            'Lumaco', 'Melipeuco', 'Nueva Imperial', 'Padre Las Casas',
            'Perquenco', 'Pitrufquén', 'Pucón', 'Purén', 'Renaico',
            'Saavedra', 'Temuco', 'Teodoro Schmidt', 'Toltén', 'Traiguén',
            'Victoria', 'Vilcún', 'Villarrica',
        ],
    },
    {
        'number': 14,
        'roman': 'XIV',
        'name': 'Los Ríos',
        'capital': 'Valdivia',
        'communes': [
            'Corral', 'Futrono', 'La Unión', 'Lago Ranco', 'Lanco',
            'Los Lagos', 'Máfil', 'Mariquina', 'Paillaco', 'Panguipulli',
            'Río Bueno', 'Valdivia',
        ],
    },
    {
        'number': 10,
        'roman': 'X',
        'name': 'Los Lagos',
        'capital': 'Puerto Montt',
        'communes': [
            'Ancud', 'Calbuco', 'Castro', 'Chaitén', 'Chonchi', 'Cochamó',
            'Curaco de Vélez', 'Dalcahue', 'Fresia', 'Frutillar',
            'Futaleufú', 'Hualaihué', 'Llanquihue', 'Los Muermos',
            'Maullín', 'Osorno', 'Palena', 'Puerto Montt', 'Puerto Octay',
            'Puerto Varas', 'Puqueldón', 'Purranque', 'Puyehue', 'Queilén',
            'Quellón', 'Quemchi', 'Quinchao', 'Río Negro',
            'San Juan de la Costa', 'San Pablo',
        ],
    },
    {
        'number': 11,
        'roman': 'XI',
        'name': 'Aysén del General Carlos Ibáñez del Campo',
        'capital': 'Coyhaique',
        'communes': [
            'Aysén', 'Chile Chico', 'Cisnes', 'Cochrane', 'Coyhaique',
            'Guaitecas', 'Lago Verde', "O'Higgins", 'Río Ibáñez', 'Tortel',
        ],
    },
    {
        'number': 12,
        'roman': 'XII',
        'name': 'Magallanes y de la Antártica Chilena',
        'capital': 'Punta Arenas',
        'communes': [
            'Antártica', 'Cabo de Hornos', 'Laguna Blanca', 'Natales',
            'Porvenir', 'Primavera', 'Punta Arenas', 'Río Verde',
            'San Gregorio', 'Timaukel', 'Torres del Paine',
        ],
    },
]

TOTAL_COMMUNES = sum(len(region['communes']) for region in CHILE_REGIONS)
