# Generated by Django 5.2.16 on 2026-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ProductType',
            field=models.CharField(max_length=55),
        ),
    ]
