# Generated by Django 5.2.16 on 2026-07-19 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carritoitem_count'),
        ('product', '0008_alter_product_compare_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(fields=('carrito', 'product'), name='unique_product_per_cart'),
        ),
    ]
