# Generated by Django 5.2.16 on 2026-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
    ]
