# Generated by Django 5.2.16 on 2026-10-01 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0013_drop_product_subclasses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('publishing', 'Publicando'), ('published', 'Publicada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], db_index=True, default='scheduled', max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('media_id', models.CharField(blank=True, default='', max_length=64)),
                ('permalink', models.URLField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_posts', to='product.product')),
            ],
            options={
                'verbose_name': 'publicación de Instagram',
                'verbose_name_plural': 'publicaciones de Instagram',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
