# Generated by Django 3.2.16 on 2023-11-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_auto_20230928_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='photo',
            field=models.ImageField(default=1, upload_to='logos/%y/%m'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
