# Generated by Django 5.0.6 on 2024-11-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20231124_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='price',
        ),
    ]
