# Generated by Django 5.2.16 on 2026-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_remove_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
