# Generated by Django 5.2.17 on 2026-09-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/%y/%m'),
        ),
    ]
