# Generated by Django 5.2.16 on 2026-10-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_timestamps'),
        ('shipping', '0007_alter_shipping_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='carrier',
            field=models.CharField(choices=[('manual', 'Precio fijo'), ('starken', 'Starken (cotizado)')], default='manual', help_text='Precio fijo, o cotizado en linea con el courier por comuna.', max_length=20),
        ),
        migrations.AddField(
            model_name='shipping',
            name='starken_delivery_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Retiro en agencia'), (2, 'A domicilio')], help_text='Solo para Starken: retiro en agencia o a domicilio.', null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='starken_service_type',
            field=models.PositiveSmallIntegerField(default=0, help_text='Solo para Starken: 0 = normal, 1 = express.'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(default='starken', max_length=20)),
                ('tracking_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('status_at', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
        ),
    ]
