# Generated by Django 5.2.16 on 2026-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_amount_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
