# Generated by Django 5.2.16 on 2026-07-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_mercadopago_webhook_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
