# Generated by Django 5.2.16 on 2026-09-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch_warned_at',
            field=models.DateTimeField(blank=True, help_text='Ultimo aviso al admin de que el plazo de despacho esta por vencer.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Primera vez que MercadoPago aprobo el pago. Null = nunca se pago.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Cuando el pedido paso a "enviado".', null=True),
        ),
    ]
