# Generated by Django 5.2.16 on 2026-10-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True, default='', max_length=2000)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('accepted', 'Aceptada'), ('refunded', 'Reembolsada'), ('rejected', 'Rechazada')], db_index=True, default='received', max_length=20)),
                ('staff_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'solicitud de retracto',
                'verbose_name_plural': 'solicitudes de retracto',
                'ordering': ['-created_at'],
            },
        ),
    ]
